# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QPushButton, QSizePolicy,
    QTabWidget, QTextBrowser, QWidget)

from filelineedit import FileLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1029, 709)
        self.triggerTypeTabs = QTabWidget(MainWindow)
        self.triggerTypeTabs.setObjectName(u"triggerTypeTabs")
        self.triggerTypeTabs.setGeometry(QRect(10, 100, 1001, 651))
        self.manual_tab = QWidget()
        self.manual_tab.setObjectName(u"manual_tab")
        self.manualAttributeGroupBox = QGroupBox(self.manual_tab)
        self.manualAttributeGroupBox.setObjectName(u"manualAttributeGroupBox")
        self.manualAttributeGroupBox.setGeometry(QRect(10, 30, 801, 501))
        self.triggerTypeTabs.addTab(self.manual_tab, "")
        self.nn_tab = QWidget()
        self.nn_tab.setObjectName(u"nn_tab")
        self.nnHyperparamGroupBox = QGroupBox(self.nn_tab)
        self.nnHyperparamGroupBox.setObjectName(u"nnHyperparamGroupBox")
        self.nnHyperparamGroupBox.setGeometry(QRect(10, 10, 791, 71))
        self.nnHyperparamLineEdit = QLineEdit(self.nnHyperparamGroupBox)
        self.nnHyperparamLineEdit.setObjectName(u"nnHyperparamLineEdit")
        self.nnHyperparamLineEdit.setGeometry(QRect(20, 30, 361, 22))
        self.nnBrowseHyperparamButton = QPushButton(self.nnHyperparamGroupBox)
        self.nnBrowseHyperparamButton.setObjectName(u"nnBrowseHyperparamButton")
        self.nnBrowseHyperparamButton.setGeometry(QRect(410, 30, 80, 23))
        self.nnClassesGroupBox = QGroupBox(self.nn_tab)
        self.nnClassesGroupBox.setObjectName(u"nnClassesGroupBox")
        self.nnClassesGroupBox.setGeometry(QRect(10, 90, 971, 391))
        self.nnClassListWidget = QListWidget(self.nnClassesGroupBox)
        self.nnClassListWidget.setObjectName(u"nnClassListWidget")
        self.nnClassListWidget.setGeometry(QRect(10, 30, 281, 171))
        self.nnStartTrainingButton = QPushButton(self.nnClassesGroupBox)
        self.nnStartTrainingButton.setObjectName(u"nnStartTrainingButton")
        self.nnStartTrainingButton.setGeometry(QRect(20, 220, 151, 23))
        self.nnSaveModelButton = QPushButton(self.nnClassesGroupBox)
        self.nnSaveModelButton.setObjectName(u"nnSaveModelButton")
        self.nnSaveModelButton.setGeometry(QRect(20, 260, 161, 23))
        self.nnConsoleTextBrowser = QTextBrowser(self.nnClassesGroupBox)
        self.nnConsoleTextBrowser.setObjectName(u"nnConsoleTextBrowser")
        self.nnConsoleTextBrowser.setGeometry(QRect(350, 40, 611, 321))
        self.nnTrainingProgressLabel = QLabel(self.nnClassesGroupBox)
        self.nnTrainingProgressLabel.setObjectName(u"nnTrainingProgressLabel")
        self.nnTrainingProgressLabel.setGeometry(QRect(350, 20, 111, 16))
        self.triggerTypeTabs.addTab(self.nn_tab, "")
        self.lvq_tab = QWidget()
        self.lvq_tab.setObjectName(u"lvq_tab")
        self.lvqHyperparamGroupBox = QGroupBox(self.lvq_tab)
        self.lvqHyperparamGroupBox.setObjectName(u"lvqHyperparamGroupBox")
        self.lvqHyperparamGroupBox.setGeometry(QRect(10, 10, 791, 71))
        self.lvqHyperparamLineEdit = QLineEdit(self.lvqHyperparamGroupBox)
        self.lvqHyperparamLineEdit.setObjectName(u"lvqHyperparamLineEdit")
        self.lvqHyperparamLineEdit.setGeometry(QRect(20, 30, 361, 22))
        self.lvqBrowseHyperparamButton = QPushButton(self.lvqHyperparamGroupBox)
        self.lvqBrowseHyperparamButton.setObjectName(u"lvqBrowseHyperparamButton")
        self.lvqBrowseHyperparamButton.setGeometry(QRect(410, 30, 80, 23))
        self.lvqClassesGroupBox = QGroupBox(self.lvq_tab)
        self.lvqClassesGroupBox.setObjectName(u"lvqClassesGroupBox")
        self.lvqClassesGroupBox.setGeometry(QRect(10, 90, 981, 371))
        self.lvqClassListWidget = QListWidget(self.lvqClassesGroupBox)
        self.lvqClassListWidget.setObjectName(u"lvqClassListWidget")
        self.lvqClassListWidget.setGeometry(QRect(10, 30, 281, 171))
        self.lvqStartTrainingButton = QPushButton(self.lvqClassesGroupBox)
        self.lvqStartTrainingButton.setObjectName(u"lvqStartTrainingButton")
        self.lvqStartTrainingButton.setGeometry(QRect(20, 220, 151, 23))
        self.lvqSaveModelButton = QPushButton(self.lvqClassesGroupBox)
        self.lvqSaveModelButton.setObjectName(u"lvqSaveModelButton")
        self.lvqSaveModelButton.setGeometry(QRect(20, 260, 161, 23))
        self.lvqConsoleTextBrowser = QTextBrowser(self.lvqClassesGroupBox)
        self.lvqConsoleTextBrowser.setObjectName(u"lvqConsoleTextBrowser")
        self.lvqConsoleTextBrowser.setGeometry(QRect(350, 40, 621, 311))
        self.lvqTrainingProgressLabel = QLabel(self.lvqClassesGroupBox)
        self.lvqTrainingProgressLabel.setObjectName(u"lvqTrainingProgressLabel")
        self.lvqTrainingProgressLabel.setGeometry(QRect(350, 20, 111, 16))
        self.triggerTypeTabs.addTab(self.lvq_tab, "")
        self.svm_tab = QWidget()
        self.svm_tab.setObjectName(u"svm_tab")
        self.svmHyperparamGroupBox = QGroupBox(self.svm_tab)
        self.svmHyperparamGroupBox.setObjectName(u"svmHyperparamGroupBox")
        self.svmHyperparamGroupBox.setGeometry(QRect(10, 20, 791, 71))
        self.svmHyperparamLineEdit = QLineEdit(self.svmHyperparamGroupBox)
        self.svmHyperparamLineEdit.setObjectName(u"svmHyperparamLineEdit")
        self.svmHyperparamLineEdit.setGeometry(QRect(20, 30, 361, 22))
        self.svmBrowseHyperparamButton = QPushButton(self.svmHyperparamGroupBox)
        self.svmBrowseHyperparamButton.setObjectName(u"svmBrowseHyperparamButton")
        self.svmBrowseHyperparamButton.setGeometry(QRect(410, 30, 80, 23))
        self.svmClassesGroupBox = QGroupBox(self.svm_tab)
        self.svmClassesGroupBox.setObjectName(u"svmClassesGroupBox")
        self.svmClassesGroupBox.setGeometry(QRect(10, 100, 981, 371))
        self.svmClassListWidget = QListWidget(self.svmClassesGroupBox)
        self.svmClassListWidget.setObjectName(u"svmClassListWidget")
        self.svmClassListWidget.setGeometry(QRect(10, 30, 281, 171))
        self.svmStartTrainingButton = QPushButton(self.svmClassesGroupBox)
        self.svmStartTrainingButton.setObjectName(u"svmStartTrainingButton")
        self.svmStartTrainingButton.setGeometry(QRect(20, 220, 151, 23))
        self.svmSaveModelButton = QPushButton(self.svmClassesGroupBox)
        self.svmSaveModelButton.setObjectName(u"svmSaveModelButton")
        self.svmSaveModelButton.setGeometry(QRect(20, 260, 161, 23))
        self.svmConsoleTextBrowser = QTextBrowser(self.svmClassesGroupBox)
        self.svmConsoleTextBrowser.setObjectName(u"svmConsoleTextBrowser")
        self.svmConsoleTextBrowser.setGeometry(QRect(350, 40, 621, 311))
        self.svmTrainingProgressLabel = QLabel(self.svmClassesGroupBox)
        self.svmTrainingProgressLabel.setObjectName(u"svmTrainingProgressLabel")
        self.svmTrainingProgressLabel.setGeometry(QRect(350, 20, 111, 16))
        self.triggerTypeTabs.addTab(self.svm_tab, "")
        self.one_svm_tab = QWidget()
        self.one_svm_tab.setObjectName(u"one_svm_tab")
        self.oneSvmHyperparamGroupBox = QGroupBox(self.one_svm_tab)
        self.oneSvmHyperparamGroupBox.setObjectName(u"oneSvmHyperparamGroupBox")
        self.oneSvmHyperparamGroupBox.setGeometry(QRect(10, 20, 791, 71))
        self.oneSvmHyperparamLineEdit = QLineEdit(self.oneSvmHyperparamGroupBox)
        self.oneSvmHyperparamLineEdit.setObjectName(u"oneSvmHyperparamLineEdit")
        self.oneSvmHyperparamLineEdit.setGeometry(QRect(30, 30, 361, 22))
        self.oneSvmBrowseHyperparamButton = QPushButton(self.oneSvmHyperparamGroupBox)
        self.oneSvmBrowseHyperparamButton.setObjectName(u"oneSvmBrowseHyperparamButton")
        self.oneSvmBrowseHyperparamButton.setGeometry(QRect(410, 30, 80, 23))
        self.oneSvmClassesGroupBox = QGroupBox(self.one_svm_tab)
        self.oneSvmClassesGroupBox.setObjectName(u"oneSvmClassesGroupBox")
        self.oneSvmClassesGroupBox.setGeometry(QRect(10, 100, 981, 371))
        self.oneSvmClassListWidget = QListWidget(self.oneSvmClassesGroupBox)
        self.oneSvmClassListWidget.setObjectName(u"oneSvmClassListWidget")
        self.oneSvmClassListWidget.setGeometry(QRect(10, 30, 281, 171))
        self.oneSvmStartTrainingButton = QPushButton(self.oneSvmClassesGroupBox)
        self.oneSvmStartTrainingButton.setObjectName(u"oneSvmStartTrainingButton")
        self.oneSvmStartTrainingButton.setGeometry(QRect(20, 220, 151, 23))
        self.oneSvmSaveModelButton = QPushButton(self.oneSvmClassesGroupBox)
        self.oneSvmSaveModelButton.setObjectName(u"oneSvmSaveModelButton")
        self.oneSvmSaveModelButton.setGeometry(QRect(20, 260, 161, 23))
        self.oneSvmConsoleTextBrowser = QTextBrowser(self.oneSvmClassesGroupBox)
        self.oneSvmConsoleTextBrowser.setObjectName(u"oneSvmConsoleTextBrowser")
        self.oneSvmConsoleTextBrowser.setGeometry(QRect(350, 40, 621, 311))
        self.oneSvmTrainingProgressLabel = QLabel(self.oneSvmClassesGroupBox)
        self.oneSvmTrainingProgressLabel.setObjectName(u"oneSvmTrainingProgressLabel")
        self.oneSvmTrainingProgressLabel.setGeometry(QRect(350, 20, 111, 16))
        self.triggerTypeTabs.addTab(self.one_svm_tab, "")
        self.browseInputButton = QPushButton(MainWindow)
        self.browseInputButton.setObjectName(u"browseInputButton")
        self.browseInputButton.setGeometry(QRect(480, 20, 80, 23))
        self.inputFileLineEdit = FileLineEdit(MainWindow)
        self.inputFileLineEdit.setObjectName(u"inputFileLineEdit")
        self.inputFileLineEdit.setGeometry(QRect(140, 20, 321, 22))
        self.inputLabel = QLabel(MainWindow)
        self.inputLabel.setObjectName(u"inputLabel")
        self.inputLabel.setGeometry(QRect(30, 20, 121, 16))
        self.loadInputButton = QPushButton(MainWindow)
        self.loadInputButton.setObjectName(u"loadInputButton")
        self.loadInputButton.setGeometry(QRect(30, 60, 131, 31))

        self.retranslateUi(MainWindow)

        self.triggerTypeTabs.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.manualAttributeGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Feature Intervals", None))
        self.triggerTypeTabs.setTabText(self.triggerTypeTabs.indexOf(self.manual_tab), QCoreApplication.translate("MainWindow", u"Manual interval trigger", None))
        self.nnHyperparamGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Import hyperparameter file:", None))
        self.nnBrowseHyperparamButton.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.nnClassesGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Select Classes For Trigger", None))
        self.nnStartTrainingButton.setText(QCoreApplication.translate("MainWindow", u"Start Training", None))
        self.nnSaveModelButton.setText(QCoreApplication.translate("MainWindow", u"Save Trained Model", None))
        self.nnTrainingProgressLabel.setText(QCoreApplication.translate("MainWindow", u"Training log:", None))
        self.triggerTypeTabs.setTabText(self.triggerTypeTabs.indexOf(self.nn_tab), QCoreApplication.translate("MainWindow", u"NN trigger", None))
        self.lvqHyperparamGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Import hyperparameter file:", None))
        self.lvqBrowseHyperparamButton.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.lvqClassesGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Select Classes For Trigger", None))
        self.lvqStartTrainingButton.setText(QCoreApplication.translate("MainWindow", u"Start Training", None))
        self.lvqSaveModelButton.setText(QCoreApplication.translate("MainWindow", u"Save Trained Model", None))
        self.lvqTrainingProgressLabel.setText(QCoreApplication.translate("MainWindow", u"Training log:", None))
        self.triggerTypeTabs.setTabText(self.triggerTypeTabs.indexOf(self.lvq_tab), QCoreApplication.translate("MainWindow", u"LVQ trigger", None))
        self.svmHyperparamGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Import hyperparameter file:", None))
        self.svmBrowseHyperparamButton.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.svmClassesGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Select Classes For Trigger", None))
        self.svmStartTrainingButton.setText(QCoreApplication.translate("MainWindow", u"Start Training", None))
        self.svmSaveModelButton.setText(QCoreApplication.translate("MainWindow", u"Save Trained Model", None))
        self.svmTrainingProgressLabel.setText(QCoreApplication.translate("MainWindow", u"Training log:", None))
        self.triggerTypeTabs.setTabText(self.triggerTypeTabs.indexOf(self.svm_tab), QCoreApplication.translate("MainWindow", u"SVM trigger", None))
        self.oneSvmHyperparamGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Import hyperparameter file:", None))
        self.oneSvmBrowseHyperparamButton.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.oneSvmClassesGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Loaded classes:", None))
        self.oneSvmStartTrainingButton.setText(QCoreApplication.translate("MainWindow", u"Start Training", None))
        self.oneSvmSaveModelButton.setText(QCoreApplication.translate("MainWindow", u"Save Trained Model", None))
        self.oneSvmTrainingProgressLabel.setText(QCoreApplication.translate("MainWindow", u"Training log:", None))
        self.triggerTypeTabs.setTabText(self.triggerTypeTabs.indexOf(self.one_svm_tab), QCoreApplication.translate("MainWindow", u"ONE CLASS SVM trigger", None))
        self.browseInputButton.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.inputFileLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"<existing \".wf\" file>", None))
        self.inputLabel.setText(QCoreApplication.translate("MainWindow", u"Select input file:", None))
        self.loadInputButton.setText(QCoreApplication.translate("MainWindow", u"Load selected file", None))
    # retranslateUi

